on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write
  packages: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
      - name: Clone
        uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        if: ${{ steps.release.outputs.release_created }}
        with:
          node-version: 18.x
          registry-url: 'https://npm.pkg.github.com'
          scope: '@scribelabsai'
      - name: Install deps
        run: npm install
        if: ${{ steps.release.outputs.release_created }}
      - name: Build source
        run: npm run build:lib && npm run build:bin
        if: ${{ steps.release.outputs.release_created }}
      - name: Publish
        run: npm publish --access public
        if: ${{ steps.release.outputs.release_created }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
