# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test & Coverage

on:
  push:
    branches: [master]
  pull_request:
    paths:
      - '**.ts'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          scope: '@scribelabsai'
          registry-url: 'https://npm.pkg.github.com'
      - name: Install deps
        run: npm install
      - name: Run tests
        run: npm run test
